name: envcam
channels:
  - pytorch
  - conda-forge
dependencies:
  - python
  - jupyterlab
  - autopep8
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - dill
  - seaborn
  - pytorch
  - conda-lock
  - pip

